server:
  port: 7002


spring:
  application:
    name: eureka-goods

---
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
---
spring:
  config:
    activate:
      on-profile: pro
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/